package com.telecom.open_ticket;

import java.util.Date;
import com.telecom.Issue;
import com.telecom.cep.AlertEvent;

/*
declare AlertEvent
	@role(event)
	@timestamp(_time)
end
*/

rule "Open Ticket If Rectifier Doesn't Come Back Up After 5 Minutes"
dialect "mvel"
no-loop
	when
		$rectifierIsDown: AlertEvent(
			$t0: _time,
			$neName: neName, 
			$rectifierServerSerial: serverSerial,
			$summary: summary,
			$circuit: circuit == "RECT - power",
			severity == 4,
			ncFunction == "INSERT")
		$powerIsBackUp: AlertEvent(
			$t1: _time,
			neName == $neName, 
			$acServerSerial: serverSerial,
			circuit == "AC - power",
			ncFunction == "DELETE",
			this after $rectifierIsDown)
		not( AlertEvent(
			serverSerial == $rectifierServerSerial,
			circuit == $circuit,
			ncFunction == "DELETE",
			this after [0s, 5s] $powerIsBackUp) )
		not( Issue( serverSerial == $rectifierServerSerial ) from issues.list )
	then
	    message = 
	    "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n"+
	    "@\n"+
		"@ Major alert at "+$neName+"\n"+
		"@ Summary: "+$summary+"\n"+
		"@ Rectifier with server serial "+$rectifierServerSerial+"\n"+
		"@ went down at "+(new Date($t0)))+"\n"+
		"@ AC Power with server serial "+$acServerSerial+"\n"+
		"@ went back up at "+(new Date($t1)))+"\n"+
		"@ Rectifier did not come back up after 5s"+"\n"+
		"@ Opened ticket # SNN000000088773 at "+(new Date()))+"\n"+			
		"@"+"\n"+
		"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@";
	    issues.list.add( new Issue( $rectifierServerSerial, message ) );
		System.out.println(message);
end