package com.telecom;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Issue implements Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long serverSerialNumber;

	public Issue() {
	}

	public Long getServerSerialNumber() {
		return this.serverSerialNumber;
	}

	public void setServerSerialNumber(Long serverSerialNumber) {
		this.serverSerialNumber = serverSerialNumber;
	}

	public Issue(Long serverSerialNumber) {
		this.serverSerialNumber = serverSerialNumber;
	}

}