package com.telecom;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Issue implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Issue() {
    }




}