package com.telecom;

import java.io.Serializable;
import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Issues implements Serializable {

	static final long serialVersionUID = 1L;

	private List<Issue> list;

	public Issues() {
	}

	public List<Issue> getList() {
		return this.list;
	}

	public void setList(List<Issue> list) {
		this.list = list;
	}
	
	public void create(Issue issue) {
	    list.add(issue);
	}
	
	public void delete(Integer issueId) {
	    list.remove(issueId);
	}



	public Issues(List<Issue> list) {
		this.list = list;
	}

}