package com.telecom;

import java.io.Serializable;
import java.util.HashMap<Integer,Issue>;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Issues implements Serializable {

	static final long serialVersionUID = 1L;

	private List<Issue> list;

	private Integer lastIssueId;

	public Issues() {
	}

	public HashMap<Integer, Issue> getList() {
		return this.list;
	}

	public void setList(HashMap<Integer, Issue> list) {
		this.list = list;
	}

	public Integer getLastIssueId() {
		return this.lastIssueId;
	}

	public void setLastIssueId(Integer lastIssueId) {
		this.lastIssueId = lastIssueId;
	}
	
	public Integer newIssueId() {
	    return lastIssueId++;
	}
	
	public void removeIssue(Integer issueId) {
	    list.remove(issueId);
	}

	public Issues(List<Issue> list,
			Integer lastIssueId) {
		this.list = list;
		this.lastIssueId = lastIssueId;
	}

}