package com.telecom;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Issue implements Serializable {

	static final long serialVersionUID = 1L;

	private Long serverSerial;

	public Issue() {
	}

	public Long getServerSerial() {
		return this.serverSerial;
	}

	public void setServerSerial(Long serverSerial) {
		this.serverSerial = serverSerial;
	}

	public Issue(Long serverSerial) {
		this.serverSerial = serverSerial;
	}

}