package com.telecom;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Issues implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.telecom.Issue list;

	public Issues() {
	}

	public com.telecom.Issue getList() {
		return this.list;
	}

	public void setList(com.telecom.Issue list) {
		this.list = list;
	}

	public Issues(com.telecom.Issue list) {
		this.list = list;
	}

}